image: gradle:7.2.0-jdk17-alpine
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - gradle processor:jar
    - gradle uberJar
    - java -jar build/libs/08-comparator-generator-1.0.jar